datasets:
- name: chess_example
  url:  http://fimi.uantwerpen.be/data/chess.dat
  format: fimi
  splitting_setups:
  - num_providers: 5
    strategy: IID
  - num_providers: 5
    strategy: Non-IID
    non_iid_type: quantity
    non_iid_skew_factor: 0.3
    